### ISSUE TITLE
Missing 'ramp_time' option in Volume filter doesn't trigger a parsing error

### ISSUE THREAD

**Issue by t-gh-ctrl** [HEnquist/camillagui-backend#63]
Versions: CamillaDSP 2.0.3, pyCamillaDSP 2.0.2, Backend 2.1.1

One of my (hand written) config files works perfectly fine with camilladsp and doesn't trigger any parsing issue when loaded into camillagui (either with Files/Load into Gui, or "Fetch from DSP"); but clicking on the "Filters" tab results in a blank page shown. The other tabs (pipeline, mixer, ...) work.

After a bit of bisecting, the culprit seems to be how I defined a Volume effect:

```yaml
  volume_lfetone:
    type: Volume
    parameters:
      fader: Aux1
```

Notice the lack of `ramp_time` parameter - which shouldn't be required (as per the [doc](https://github.com/HEnquist/camilladsp?tab=readme-ov-file#volume) - there's an `(*)` after this parameter and it defaults to `200`).

If I'm then saving this config from camillagui, that's what gets written:

```yaml
volume_lfetone:
    description: null
    parameters:
      fader: Aux1
      ramp_time: null
    type: Volume
```

The resulting file can be loaded back into camillagui without any parsing error, and triggers the same issue as with the missing `ramp_time` parameter. Interestingly, loading that file into camilladsp doesn't trigger any error (so I guess that either `null` is ignored, or is taken as `0`) - but I didn't want to file an almost identical issue there.

Changing `ramp_time` to a numerical value fixes the issue - ie. the filter tabs shows all the filters properly.
