### ISSUE TITLE
Shortcuts to mixer / boolean shortcuts

### ISSUE THREAD

**Issue by aqw42** [HEnquist/camillagui-backend#77]
Hi there !
First of all, thank you for this wonderfull piece of software, it works like a charm once you setup everything correctly.

I have 2 questions that i could find answer looking at example and documentation : 
- Can i set a shortcut to a mixer parameter ? If yes, can you provide a basic example ?
- Can i create boolean shortcuts, with a tickbox ?

Have a lovely day,
Theodore

**Comment by aqw42** [comment]
Oh, and something else : Is there a way to get combined filter reponse / phase / GD graph ?

**Comment by JWahle** [comment]
Hi Theodore,
I think the examples in the [gui-config.yml](https://github.com/HEnquist/camillagui-backend/blob/master/config/gui-config.yml) should have you covered.

> Can i set a shortcut to a mixer parameter ? If yes, can you provide a basic example ?

Your path will look somewhat like this: `path: ["mixers", ...]`
To find the proper path, you need to look at the YAML structure of your config.

> Can i create boolean shortcuts, with a tickbox ?

Yes, like here: https://github.com/HEnquist/camillagui-backend/blob/ef08dba2bba3c06441c884d399450b370b035cae/config/gui-config.yml#L61-L67

> Oh, and something else : Is there a way to get combined filters reponse / phase / GD graph ?

You can show graphs for each filter in the filters tab or for each filter step in the pipeline tab. If you want other graphs, they are not there, yet :) What is missing for you?

**Comment by aqw42** [comment]
Thanks for your informations, very informative
For the mixer i cannot find the relevant path, because the yaml looks like that : 
```
mixers:
  3VStereo:
    channels:
      in: 2
      out: 4
    description: null
    labels:
    - Main L
    - Main R
    - Kick
    - Sub
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
```
How can i target the relevant "dest" and "channel" ?

About the graphs, i'd love to see a combined graph with all filters graphs overlapped, like in most dsp interfaces, to see ways allcrossovers and eqs in one look. 
Do you plan to integrate realtime FFT display aswell ?

**Comment by aqw42** [comment]
Well done for the phase graph, it is a very usefull feature to have more than just frequency response

**Comment by JWahle** [comment]
If you want to e.g. mute both source channels, I think the config has to look like this:
```
- name: "Switch"
  config_elements:
  - path: ["mixers", "mapping", 0, "sources", 0, "mute"]
  - path: ["mixers", "mapping", 0, "sources", 0, "mute"]
  type: "boolean"
```
The number ordering might be the order in the yaml-structure and not the actual number of the `dest` or `channel` - I am not really sure.
So, if you want it to be robust, you could add a gain filter for the specific channels and configure a switch to mute the gain filter.
